"use client";
import{FormEvent,useEffect,useState}from"react";
import{Archive,ArrowDown,ArrowUp,CalendarDays,Check,ChevronRight,Circle,FolderPlus,Goal as GoalIcon,Home,ListTodo,Menu,Moon,PanelLeftClose,Pencil,Plus,Search,Sun,Target,Trash2,WifiOff,X}from"lucide-react";
import{usePlanar}from"@/lib/use-planar";
import{localDate,prettyDate,weekStart}from"@/lib/dates";
import type{Activity,Board,Epic,Goal,Plan,Task}from"@/lib/types";
import{Empty,Modal,Stat}from"./ui";

type View={kind:"dashboard"|"plan"|"goals"|"search"|"trash"|"board";id?:string;offset?:0|1};
export function PlanarApp({userId,email}:{userId:string;email:string}){
 const data=usePlanar(userId),[view,setView]=useState<View>({kind:"dashboard"}),[mobile,setMobile]=useState(false),[capture,setCapture]=useState(""),[captureBoard,setCaptureBoard]=useState(""),[selected,setSelected]=useState<Task|null>(null),[selectedEpic,setSelectedEpic]=useState<Epic|null>(null),[selectedGoal,setSelectedGoal]=useState<Goal|null>(null),[dialog,setDialog]=useState<"board"|"folder"|"goal"|"epic"|null>(null),[toast,setToast]=useState(""),[online,setOnline]=useState(true);
 const activeBoards=data.boards.filter(b=>!b.archived_at&&!b.trashed_at),board=view.kind==="board"?data.boards.find(b=>b.id===view.id):undefined;
 useEffect(()=>{if(!activeBoards.some(b=>b.id===captureBoard)&&activeBoards[0])setCaptureBoard(activeBoards[0].id)},[activeBoards,captureBoard]);
 useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();addEventListener("online",sync);addEventListener("offline",sync);return()=>{removeEventListener("online",sync);removeEventListener("offline",sync)}},[]);
 useEffect(()=>{let day=localDate();const check=()=>{const next=localDate();if(next!==day){day=next;void data.load()}};addEventListener("focus",check);const timer=setInterval(check,60_000);return()=>{removeEventListener("focus",check);clearInterval(timer)}},[]);
 function notify(message:string){setToast(message);setTimeout(()=>setToast(""),2500)}
 async function act(fn:()=>Promise<unknown>,message?:string){try{await fn();if(message)notify(message)}catch(e){data.setError(e instanceof Error?e.message:"Something went wrong")}}
 async function quickAdd(e:FormEvent){e.preventDefault();if(!capture.trim()||!captureBoard)return;const title=capture.trim();setCapture("");await act(()=>data.insert("tasks",{title,board_id:captureBoard,position:data.tasks.filter(t=>t.board_id===captureBoard).length}),"Task added")}
 const nav=(v:View)=>{setView(v);setMobile(false)};
 return <div className="app-shell">
  <aside className={mobile?"sidebar open":"sidebar"}>
   <div className="brand"><div className="brand-mark small">P</div><strong>Planar</strong><button className="mobile-only icon-button" onClick={()=>setMobile(false)}><PanelLeftClose/></button></div>
   <nav aria-label="Main navigation"><Nav active={view.kind==="dashboard"} icon={<Home/>} label="Dashboard" onClick={()=>nav({kind:"dashboard"})}/><Nav active={view.kind==="plan"&&view.offset===0} icon={<Target/>} label="Today" onClick={()=>nav({kind:"plan",offset:0})}/><Nav active={view.kind==="plan"&&view.offset===1} icon={<CalendarDays/>} label="Plan tomorrow" onClick={()=>nav({kind:"plan",offset:1})}/><Nav active={view.kind==="goals"} icon={<GoalIcon/>} label="Goals" onClick={()=>nav({kind:"goals"})}/><Nav active={view.kind==="search"} icon={<Search/>} label="Search" onClick={()=>nav({kind:"search"})}/></nav>
   <div className="side-heading"><span>Boards</span><button onClick={()=>setDialog("folder")} aria-label="New folder"><FolderPlus/></button><button onClick={()=>setDialog("board")} aria-label="New board"><Plus/></button></div>
   <div className="board-tree">{data.folders.map(f=><section key={f.id}><p className="folder-name">{f.name}<button aria-label={"Delete "+f.name} onClick={()=>act(()=>data.remove("folders",f.id),"Folder removed; boards moved to Unfiled")}><X/></button></p>{activeBoards.filter(b=>b.folder_id===f.id).map(b=><BoardLink key={b.id} board={b} active={view.id===b.id} onClick={()=>nav({kind:"board",id:b.id})}/>)}</section>)}<section><p className="folder-name">Unfiled</p>{activeBoards.filter(b=>!b.folder_id).map(b=><BoardLink key={b.id} board={b} active={view.id===b.id} onClick={()=>nav({kind:"board",id:b.id})}/>)}</section></div>
   <div className="sidebar-bottom"><Nav active={view.kind==="trash"} icon={<Trash2/>} label="Archive & Trash" onClick={()=>nav({kind:"trash"})}/><div className="account"><span>{email.slice(0,1).toUpperCase()}</span><div><strong>{email.split("@")[0]}</strong><small>Private workspace</small></div><form action="/api/auth/signout" method="post"><button>Sign out</button></form></div></div>
  </aside>
  <main className="workspace">
   <header className="topbar"><button className="mobile-only icon-button" onClick={()=>setMobile(true)}><Menu/></button><form className="quick-capture" onSubmit={quickAdd}><Plus/><input aria-label="Quick capture task" placeholder="Add a task…" value={capture} onChange={e=>setCapture(e.target.value)}/><select aria-label="Destination board" value={captureBoard} onChange={e=>setCaptureBoard(e.target.value)}>{activeBoards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button disabled={!online||!capture.trim()}>Add</button></form><ThemeButton/></header>
   {!online&&<div className="offline"><WifiOff/> You’re offline. Your input stays here, but changes cannot save until you reconnect.</div>}
   {data.loading?<div className="loading">Gathering your plan…</div>:<>{view.kind==="dashboard"&&<Dashboard {...data} onNavigate={nav} onTask={setSelected}/>} {view.kind==="plan"&&<PlanView offset={view.offset??0} data={data} onTask={setSelected}/>} {view.kind==="board"&&board&&<BoardView board={board} data={data} onTask={setSelected} onNewEpic={()=>setDialog("epic")} onEpic={setSelectedEpic} onNavigate={nav}/>} {view.kind==="goals"&&<GoalsView data={data} onNew={()=>setDialog("goal")} onEdit={setSelectedGoal}/>} {view.kind==="search"&&<SearchView data={data} onTask={setSelected}/>} {view.kind==="trash"&&<LifecycleView data={data}/>}</>}
  </main>
  {selectedEpic&&<EpicDetail epic={data.epics.find(e=>e.id===selectedEpic.id)??selectedEpic} data={data} onTask={setSelected} onClose={()=>setSelectedEpic(null)}/>}
  {selectedGoal&&<GoalDetail goal={data.goals.find(g=>g.id===selectedGoal.id)??selectedGoal} data={data} onClose={()=>setSelectedGoal(null)}/>}
  {selected&&<TaskDetail task={data.tasks.find(t=>t.id===selected.id)??selected} data={data} onClose={()=>setSelected(null)}/>}
  {dialog&&<CreateDialog kind={dialog} board={board} data={data} onClose={()=>setDialog(null)}/>}
  {data.error&&<div className="toast toast-error" role="alert"><span>{data.error}</span><button onClick={()=>data.setError("")}>Dismiss</button></div>}
  {toast&&<div className="toast toast-success"><Check/>{toast}</div>}
 </div>
}
function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={active?"nav-item active":"nav-item"} onClick={onClick}>{icon}<span>{label}</span></button>}
function BoardLink({board,active,onClick}:{board:Board;active:boolean;onClick:()=>void}){return <button className={active?"board-link active":"board-link"} onClick={onClick}><span className="board-dot"/>{board.name}<ChevronRight/></button>}
function ThemeButton(){const[theme,setTheme]=useState("system");useEffect(()=>setTheme(localStorage.getItem("planar-theme")||"system"),[]);function cycle(){const next=theme==="system"?"light":theme==="light"?"dark":"system";setTheme(next);localStorage.setItem("planar-theme",next);document.documentElement.dataset.theme=next}return <button className="icon-button" onClick={cycle} aria-label={"Theme: "+theme}>{theme==="light"?<Sun/>:theme==="dark"?<Moon/>:<span className="system-icon">◐</span>}</button>}
function PageHead({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}){return <div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</div>}
function TaskRow({task,onClick,compact=false}:{task:Task;onClick:()=>void;compact?:boolean}){return <button className={"task-row "+(task.status==="done"?"done ":"")+(compact?"compact":"")} onClick={onClick}><span className="check">{task.status==="done"?<Check/>:<Circle/>}</span><span className="task-main"><strong>{task.title}</strong><small>{[task.priority!=="normal"&&task.priority,task.effort&&task.effort+" effort",task.due_date&&"Due "+task.due_date].filter(Boolean).join(" · ")}</small></span><ChevronRight/></button>}
function Dashboard({boards,tasks,goals,plans,activity,onNavigate,onTask}:{boards:Board[];tasks:Task[];goals:Goal[];plans:Plan[];activity:Activity[];onNavigate:(v:View)=>void;onTask:(t:Task)=>void}){
 const today=localDate(),plan=plans.find(p=>p.plan_date===today),items=(plan?.daily_plan_items??[]).map(i=>tasks.find(t=>t.id===i.task_id)).filter(Boolean)as Task[],remaining=items.filter(t=>t.status!=="done"),activeGoals=goals.filter(g=>g.status==="active"&&g.start_date<=today&&g.end_date>=today),completedWeek=activity.filter(a=>a.event==="completed"&&a.occurred_at.slice(0,10)>=weekStart()).length,activeBoardIds=new Set(boards.filter(b=>!b.archived_at&&!b.trashed_at).map(b=>b.id)),outstanding=tasks.filter(t=>t.status!=="done"&&!t.trashed_at&&!t.archived_at&&!t.parent_id&&activeBoardIds.has(t.board_id)).sort((a,b)=>(a.due_date??"9999").localeCompare(b.due_date??"9999"));
 return <div className="page"><PageHead eyebrow={prettyDate(today)} title={plan?.focus||"What matters today?"} action={<button className="button secondary" onClick={()=>onNavigate({kind:"plan",offset:1})}>Plan tomorrow <ChevronRight/></button>}/><div className="stats-grid"><Stat label="Today's plan" value={items.filter(t=>t.status==="done").length+"/"+items.length} detail="tasks complete"/><Stat label="This week" value={completedWeek} detail="completion events"/><Stat label="Active goals" value={activeGoals.length} detail="in this period"/><Stat label="Outstanding" value={outstanding.length} detail="unfinished tasks"/></div><div className="dashboard-grid"><section className="card primary-card"><p className="eyebrow">Start here</p>{remaining[0]?<><h2>{remaining[0].title}</h2><p>{remaining[0].notes||"Your first unfinished task for today."}</p><button className="button" onClick={()=>onTask(remaining[0])}>Open task</button></>:<Empty icon={<Check/>} title="The path is clear">Add something to Today or enjoy the breathing room.</Empty>}</section><section className="card"><div className="section-head"><h2>Today</h2><button onClick={()=>onNavigate({kind:"plan",offset:0})}>View plan</button></div>{items.slice(0,5).map(t=><TaskRow key={t.id} task={t} onClick={()=>onTask(t)}/>)}{!items.length&&<p className="muted">Nothing planned yet.</p>}</section><section className="card"><div className="section-head"><h2>Current goals</h2><button onClick={()=>onNavigate({kind:"goals"})}>All goals</button></div>{activeGoals.slice(0,4).map(g=><div className="goal-row" key={g.id}><Target/><div><strong>{g.title}</strong><small>Through {g.end_date}</small></div></div>)}{!activeGoals.length&&<p className="muted">No active goals for today.</p>}</section><section className="card outstanding-card"><div className="section-head"><div><p className="eyebrow">Across active boards</p><h2>Outstanding work</h2></div><button onClick={()=>onNavigate({kind:"search"})}>View all</button></div>{outstanding.slice(0,5).map(t=><TaskRow key={t.id} task={t} onClick={()=>onTask(t)}/>)}{!outstanding.length&&<Empty icon={<ListTodo/>} title="All caught up">There are no unfinished tasks on active boards.</Empty>}</section></div></div>
}
function PlanView({offset,data,onTask}:{offset:0|1;data:ReturnType<typeof usePlanar>;onTask:(t:Task)=>void}){
 const date=localDate(offset),existing=data.plans.find(p=>p.plan_date===date),[focus,setFocus]=useState(existing?.focus??""),[ids,setIds]=useState<string[]>(existing?.daily_plan_items.flatMap(i=>i.task_id?[i.task_id]:[])??[]),[saving,setSaving]=useState(false),[picker,setPicker]=useState(false);
 useEffect(()=>{setFocus(existing?.focus??"");setIds(existing?.daily_plan_items.flatMap(i=>i.task_id?[i.task_id]:[])??[])},[existing?.id,existing?.version,date]);
 const items=ids.map(id=>data.tasks.find(t=>t.id===id)).filter(Boolean)as Task[];
 async function save(nextIds=ids,nextFocus=focus){setSaving(true);try{await data.savePlan(date,nextFocus,nextIds,existing?.version)}catch(e){data.setError(e instanceof Error?e.message:"Plan could not save")}finally{setSaving(false)}}
 function move(i:number,d:number){const next=[...ids],[x]=next.splice(i,1);next.splice(i+d,0,x);setIds(next);void save(next)}
 return <div className="page narrow"><PageHead eyebrow={offset?"Tomorrow":prettyDate(date)} title={offset?"Plan tomorrow":"Today"} action={<span className="save-state">{saving?"Saving…":"Saved"}</span>}/>{offset===1&&<CarryForward data={data} ids={ids} add={id=>{const next=[...ids,id];setIds(next);void save(next)}}/>}<label className="focus-field"><Target/><span>Daily focus<input placeholder="One intention for the day…" value={focus} onChange={e=>setFocus(e.target.value)} onBlur={()=>void save(ids,focus)}/></span></label><div className="section-head"><h2>{offset?"Tomorrow’s order":"Your checklist"}</h2><button className="button secondary" onClick={()=>setPicker(true)}><Plus/>Choose tasks</button></div><div className="plan-list">{items.map((t,i)=><div className="plan-item" key={t.id}><TaskRow task={t} onClick={()=>onTask(t)}/><div className="reorder"><button disabled={i===0} onClick={()=>move(i,-1)} aria-label={"Move "+t.title+" up"}><ArrowUp/></button><button disabled={i===items.length-1} onClick={()=>move(i,1)} aria-label={"Move "+t.title+" down"}><ArrowDown/></button><button onClick={()=>{const next=ids.filter(id=>id!==t.id);setIds(next);void save(next)}} aria-label={"Remove "+t.title}><X/></button></div></div>)}</div>{!items.length&&<Empty icon={<CalendarDays/>} title="An open day">Choose tasks from any board. Nothing carries forward unless you decide it should.</Empty>}{picker&&<TaskPicker tasks={data.tasks.filter(t=>!t.trashed_at&&!t.archived_at&&data.boards.some(b=>b.id===t.board_id&&!b.trashed_at&&!b.archived_at))} boards={data.boards} selected={ids} onToggle={id=>{const next=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];setIds(next);void save(next)}} onClose={()=>setPicker(false)}/>}</div>
}
function CarryForward({data,ids,add}:{data:ReturnType<typeof usePlanar>;ids:string[];add:(id:string)=>void}){const today=data.plans.find(p=>p.plan_date===localDate()),left=(today?.daily_plan_items??[]).map(i=>data.tasks.find(t=>t.id===i.task_id)).filter((t):t is Task=>!!t&&t.status!=="done"&&!ids.includes(t.id));if(!left.length)return null;return <div className="carry"><div><strong>Review today’s unfinished work</strong><p>Nothing moves automatically.</p></div>{left.map(t=><button key={t.id} onClick={()=>add(t.id)}><Plus/>{t.title}</button>)}</div>}
function TaskPicker({tasks,boards,selected,onToggle,onClose}:{tasks:Task[];boards:Board[];selected:string[];onToggle:(id:string)=>void;onClose:()=>void}){const[q,setQ]=useState("");return <Modal title="Choose tasks" onClose={onClose}><input className="wide-input" autoFocus placeholder="Find a task…" value={q} onChange={e=>setQ(e.target.value)}/><div className="picker-list">{tasks.filter(t=>t.title.toLowerCase().includes(q.toLowerCase())).map(t=><label key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={()=>onToggle(t.id)}/><span><strong>{t.title}</strong><small>{boards.find(b=>b.id===t.board_id)?.name}</small></span></label>)}</div></Modal>}

function BoardView({board,data,onTask,onNewEpic,onEpic,onNavigate}:{board:Board;data:ReturnType<typeof usePlanar>;onTask:(t:Task)=>void;onNewEpic:()=>void;onEpic:(e:Epic)=>void;onNavigate:(v:View)=>void}){
 const[title,setTitle]=useState(""),[view,setListView]=useState<"list"|"kanban">("list"),tasks=data.tasks.filter(t=>t.board_id===board.id&&!t.trashed_at&&!t.archived_at),epics=data.epics.filter(e=>e.board_id===board.id&&!e.trashed_at&&!e.archived_at);
 async function add(e:FormEvent){e.preventDefault();if(!title.trim())return;const value=title.trim();setTitle("");try{await data.insert("tasks",{title:value,board_id:board.id,position:tasks.length})}catch(e){data.setError(e instanceof Error?e.message:"Task could not be added")}}
 async function archive(){const planned=data.plans.some(p=>p.plan_date>=localDate()&&p.daily_plan_items.some(i=>tasks.some(t=>t.id===i.task_id&&t.status!=="done")));if(planned&&!confirm("This board has unfinished work in current or future plans. Archive it while preserving those plan entries?"))return;await data.update("boards",board.id,{archived_at:new Date().toISOString()});onNavigate({kind:"dashboard"})}
 async function trash(){const active=data.boards.filter(b=>!b.archived_at&&!b.trashed_at);if(active.length<=1){data.setError("Create another board before moving your final active board to Trash.");return}if(!confirm("Move this board to Trash? Its tasks and epics will be hidden but preserved, and restoring the board brings them back."))return;await data.update("boards",board.id,{trashed_at:new Date().toISOString()});onNavigate({kind:"dashboard"})}
 return <div className="page"><PageHead eyebrow={data.folders.find(f=>f.id===board.folder_id)?.name||"Unfiled board"} title={board.name} action={<div className="actions"><button className="icon-button" onClick={()=>setListView(view==="list"?"kanban":"list")} aria-label="Switch view">{view==="list"?<LayoutColumns/>:<LayoutRows/>}</button><button className="button secondary" onClick={onNewEpic}><Plus/>New epic</button><button className="icon-button" onClick={()=>void archive()} aria-label="Archive board"><Archive/></button><button className="icon-button danger-icon" onClick={()=>void trash()} aria-label="Move board to Trash"><Trash2/></button></div>}/>
 <form className="board-capture" onSubmit={add}><Plus/><input placeholder={"Add a task to "+board.name} value={title} onChange={e=>setTitle(e.target.value)}/><button className="button">Add task</button></form>
 {view==="list"?<div className="group-list"><TaskGroup title="Standalone" tasks={tasks.filter(t=>!t.epic_id&&!t.parent_id)} onTask={onTask}/>{epics.map(e=><TaskGroup key={e.id} title={e.title} subtitle={tasks.filter(t=>t.epic_id===e.id&&t.status==="done").length+"/"+tasks.filter(t=>t.epic_id===e.id).length+" complete"} tasks={tasks.filter(t=>t.epic_id===e.id&&!t.parent_id)} onTask={onTask} onManage={()=>onEpic(e)}/>)}</div>:<div className="kanban">{(["todo","in_progress","done"]as const).map(s=><section key={s}><h3>{s==="in_progress"?"In progress":s[0].toUpperCase()+s.slice(1)}</h3>{tasks.filter(t=>t.status===s&&!t.parent_id).map(t=><TaskRow key={t.id} task={t} compact onClick={()=>onTask(t)}/>)}</section>)}</div>}
 {!tasks.length&&<Empty icon={<Circle/>} title="A fresh board">Capture a task with only a title. Add structure when it earns its place.</Empty>}</div>
}
function LayoutColumns(){return <span aria-hidden>▦</span>}function LayoutRows(){return <span aria-hidden>☷</span>}
function TaskGroup({title,subtitle,tasks,onTask,onManage}:{title:string;subtitle?:string;tasks:Task[];onTask:(t:Task)=>void;onManage?:()=>void}){return <section className="task-group"><div className="section-head epic-heading"><div><h2>{title}</h2>{subtitle&&<small>{subtitle}</small>}</div>{onManage&&<button className="manage-link" onClick={onManage}>Manage epic <ChevronRight/></button>}</div>{tasks.map(t=><TaskRow key={t.id} task={t} onClick={()=>onTask(t)}/>)}{!tasks.length&&<p className="muted">No tasks in this group.</p>}</section>}

function TaskDetail({task,data,onClose}:{task:Task;data:ReturnType<typeof usePlanar>;onClose:()=>void}){
 const[form,setForm]=useState(task),[sub,setSub]=useState(""),[link,setLink]=useState(""),[busy,setBusy]=useState(false),children=data.tasks.filter(t=>t.parent_id===task.id&&!t.trashed_at),other=data.tasks.filter(t=>t.id!==task.id&&!t.parent_id&&!t.trashed_at);
 async function save(){setBusy(true);try{const values={title:form.title.trim(),notes:form.notes,status:form.status,effort:form.effort||null,priority:form.priority,due_date:form.due_date||null,board_id:form.board_id,epic_id:form.epic_id||null};const changes=Object.fromEntries(Object.entries(values).filter(([key,value])=>value!==task[key as keyof Task]));if(Object.keys(changes).length)await data.update("tasks",task.id,changes);onClose()}catch(e){data.setError(e instanceof Error?e.message:"Could not save")}finally{setBusy(false)}}
 async function status(){if(task.status!=="done"&&children.some(t=>t.status!=="done")&&!confirm("Some subtasks are unfinished. Complete the parent without completing them?"))return;const next=task.status==="done"?"todo":"done";await data.update("tasks",task.id,{status:next});setForm({...form,status:next})}
 async function addSub(e:FormEvent){e.preventDefault();if(!sub.trim())return;await data.insert("tasks",{title:sub.trim(),board_id:task.board_id,epic_id:task.epic_id,parent_id:task.id,position:children.length});setSub("")}
 async function addLink(){if(!link)return;try{await data.insert("task_relationships",{source_task_id:task.id,target_task_id:link,kind:"blocked_by"});setLink("")}catch(e){data.setError(e instanceof Error?e.message:"Could not add dependency")}}
 return <Modal title="Task details" onClose={onClose}><div className="task-detail"><button className={task.status==="done"?"complete-toggle done":"complete-toggle"} onClick={()=>void status()}>{task.status==="done"?<Check/>:<Circle/>}{task.status==="done"?"Completed":"Mark complete"}</button><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-grid"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Task["status"]})}><option value="todo">Todo</option><option value="in_progress">In progress</option><option value="done">Done</option></select></label><label>Board<select value={form.board_id} onChange={e=>setForm({...form,board_id:e.target.value,epic_id:null})}>{data.boards.filter(b=>!b.trashed_at&&!b.archived_at).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Epic<select value={form.epic_id??""} onChange={e=>setForm({...form,epic_id:e.target.value||null})}><option value="">Standalone</option>{data.epics.filter(ep=>ep.board_id===form.board_id&&!ep.trashed_at).map(ep=><option key={ep.id} value={ep.id}>{ep.title}</option>)}</select></label><label>Effort<select value={form.effort??""} onChange={e=>setForm({...form,effort:(e.target.value||null)as Task["effort"]})}><option value="">Not set</option><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Task["priority"]})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>Due date<input type="date" value={form.due_date??""} onChange={e=>setForm({...form,due_date:e.target.value||null})}/></label></div><label>Notes<textarea rows={5} placeholder="Add any useful context…" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
 <GoalLinks kind="task" entityId={task.id} data={data}/>
 <section><h3>Subtasks</h3>{children.map(t=><TaskRow key={t.id} task={t} compact onClick={()=>{}}/>)}{!task.parent_id&&<form className="inline-form" onSubmit={addSub}><input placeholder="Add a subtask…" value={sub} onChange={e=>setSub(e.target.value)}/><button><Plus/></button></form>}</section>
 <section><h3>Blocked by</h3><div className="inline-form"><select value={link} onChange={e=>setLink(e.target.value)}><option value="">Choose task…</option>{other.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button type="button" onClick={()=>void addLink()}><Plus/></button></div><small>Dependencies warn; they do not prevent progress.</small></section>
 <div className="modal-actions"><button className="danger-link" onClick={()=>{if(confirm("Move this task to Trash?"))void data.update("tasks",task.id,{trashed_at:new Date().toISOString()}).then(onClose)}}><Trash2/>Move to Trash</button><button className="button" disabled={busy||!form.title.trim()} onClick={()=>void save()}>{busy?"Saving…":"Save changes"}</button></div></div></Modal>
}

function EpicDetail({epic,data,onTask,onClose}:{epic:Epic;data:ReturnType<typeof usePlanar>;onTask:(t:Task)=>void;onClose:()=>void}){
 const[title,setTitle]=useState(epic.title),[notes,setNotes]=useState(epic.notes),[boardId,setBoardId]=useState(epic.board_id),[newTask,setNewTask]=useState(""),[pick,setPick]=useState("");
 const assigned=data.tasks.filter(t=>t.epic_id===epic.id&&!t.trashed_at&&!t.parent_id),available=data.tasks.filter(t=>t.board_id===epic.board_id&&!t.epic_id&&!t.parent_id&&!t.trashed_at&&!t.archived_at);
 async function save(){try{if(boardId!==epic.board_id)await data.rpc("move_epic",{p_epic_id:epic.id,p_board_id:boardId});await data.update("epics",epic.id,{title:title.trim(),notes});onClose()}catch(e){data.setError(e instanceof Error?e.message:"Could not save epic")}}
 async function createTask(e:FormEvent){e.preventDefault();if(!newTask.trim())return;try{await data.insert("tasks",{title:newTask.trim(),board_id:epic.board_id,epic_id:epic.id,position:assigned.length});setNewTask("")}catch(e){data.setError(e instanceof Error?e.message:"Could not create task")}}
 async function assign(){if(!pick)return;try{await data.update("tasks",pick,{epic_id:epic.id});setPick("")}catch(e){data.setError(e instanceof Error?e.message:"Could not assign task")}}
 async function trash(){if(!confirm("Move this epic to Trash? Its tasks will become standalone on the same board."))return;try{await data.rpc("trash_epic",{p_epic_id:epic.id});onClose()}catch(e){data.setError(e instanceof Error?e.message:"Could not trash epic")}}
 return <Modal title="Manage epic" onClose={onClose}><div className="task-detail epic-detail"><GoalLinks kind="epic" entityId={epic.id} data={data}/><label>Epic title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Notes<textarea rows={3} placeholder="What outcome does this epic support?" value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>Board<select value={boardId} onChange={e=>setBoardId(e.target.value)}>{data.boards.filter(b=>!b.archived_at&&!b.trashed_at).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><small>Moving an epic moves all its assigned tasks and subtasks.</small></label><section className="epic-tasks"><div className="section-head"><div><p className="eyebrow">Epic tasks</p><h3>{assigned.length} assigned</h3></div></div>{assigned.map(t=><div className="epic-task-line" key={t.id}><TaskRow task={t} compact onClick={()=>onTask(t)}/><button onClick={()=>void data.update("tasks",t.id,{epic_id:null})} aria-label={"Remove "+t.title+" from epic"}><X/></button></div>)}{!assigned.length&&<p className="muted">No tasks yet. Create one here or assign an existing standalone task.</p>}<form className="inline-form epic-create" onSubmit={createTask}><input placeholder="Create a task in this epic…" value={newTask} onChange={e=>setNewTask(e.target.value)}/><button aria-label="Create task"><Plus/></button></form>{available.length>0&&<div className="inline-form"><select value={pick} onChange={e=>setPick(e.target.value)}><option value="">Assign an existing task…</option>{available.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button type="button" onClick={()=>void assign()} aria-label="Assign task"><Plus/></button></div>}</section><div className="modal-actions"><button className="danger-link" onClick={()=>void trash()}><Trash2/>Move epic to Trash</button><button className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={!title.trim()} onClick={()=>void save()}>Save epic</button></div></div></Modal>
}

const goalLabels:Record<Goal["period"],string>={week:"This week",month:"This month",three_months:"3 months",six_months:"6 months",year:"1 year",custom:"Custom"};
function GoalLinks({kind,entityId,data}:{kind:"task"|"epic";entityId:string;data:ReturnType<typeof usePlanar>}){
 const[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),linked=new Set(kind==="task"?data.goalTasks.filter(l=>l.task_id===entityId).map(l=>l.goal_id):data.goalEpics.filter(l=>l.epic_id===entityId).map(l=>l.goal_id)),goals=data.goals.filter(g=>g.status==="active"||linked.has(g.id));
 async function toggle(goalId:string,checked:boolean){setBusy(true);setSaved(false);try{await data.setGoalLink(kind,entityId,goalId,checked);setSaved(true)}catch(e){data.setError(e&&typeof e==="object"&&"message" in e?String(e.message):"Could not update goal link")}finally{setBusy(false)}}
 return <section className="goal-links"><div className="section-head"><h3>Supporting goals</h3><small role="status">{busy?"Saving…":saved?"Saved":""}</small></div><p className="muted">Link this {kind} to a goal.</p><div className="picker-list">{goals.map(g=><label key={g.id}><input type="checkbox" disabled={busy} checked={linked.has(g.id)} onChange={e=>void toggle(g.id,e.target.checked)}/><span><strong>{g.title}</strong><small>Due {new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",timeZone:"UTC"}).format(new Date(g.end_date+"T12:00:00Z"))}</small></span></label>)}</div>{!goals.length&&<p className="muted">Create a goal to link this {kind}.</p>}</section>
}
function GoalWork({goal,data}:{goal:Goal;data:ReturnType<typeof usePlanar>}){
 const epicIds=new Set(data.goalEpics.filter(l=>l.goal_id===goal.id).map(l=>l.epic_id)),taskIds=new Set(data.goalTasks.filter(l=>l.goal_id===goal.id).map(l=>l.task_id)),boards=new Set(data.boards.filter(b=>!b.trashed_at&&!b.archived_at).map(b=>b.id)),epics=data.epics.filter(e=>epicIds.has(e.id)&&!e.trashed_at&&!e.archived_at&&boards.has(e.board_id)),visibleEpicIds=new Set(epics.map(e=>e.id)),tasks=data.tasks.filter(t=>!t.trashed_at&&!t.archived_at&&boards.has(t.board_id)&&(taskIds.has(t.id)||!!t.epic_id&&visibleEpicIds.has(t.epic_id)));
 return <section><h3>Supporting work</h3><p className="muted">{tasks.filter(t=>t.status==="done").length} / {tasks.length} linked tasks complete · {epics.length} linked epics</p>{epics.map(e=><p key={e.id}><strong>{e.title}</strong> <small className="muted">Epic</small></p>)}{tasks.map(t=><p key={t.id}>{t.status==="done"?"✓ ":"○ "}{t.title}</p>)}{!epics.length&&!tasks.length&&<p className="muted">Link tasks or epics from their details to see supporting work here.</p>}<small className="muted">Archived and trashed work is hidden. Completing work does not automatically achieve this goal.</small></section>
}
function GoalsView({data,onNew,onEdit}:{data:ReturnType<typeof usePlanar>;onNew:()=>void;onEdit:(goal:Goal)=>void}){return <div className="page"><PageHead eyebrow="Outcomes, not scores" title="Goals" action={<button className="button" onClick={onNew}><Plus/>New goal</button>}/><div className="goal-grid">{data.goals.map(g=><article className={"goal-card "+g.status} key={g.id}><div><span className="pill">{goalLabels[g.period]}</span><span className="goal-status">{g.status}</span></div><h2>{g.title}</h2><p>{g.description||"No description"}</p><small>{g.start_date} → {g.end_date}</small><div className="goal-actions"><button onClick={()=>onEdit(g)}><Pencil/>Edit</button>{g.status==="active"&&<button onClick={()=>void data.update("goals",g.id,{status:"achieved",achieved_at:new Date().toISOString()})}><Check/>Mark achieved</button>}</div></article>)}</div>{!data.goals.length&&<Empty icon={<Target/>} title="Name the outcome">Set a horizon, then keep the goal active until the outcome is genuinely achieved.</Empty>}</div>}

function GoalDetail({goal,data,onClose}:{goal:Goal;data:ReturnType<typeof usePlanar>;onClose:()=>void}){
 const[form,setForm]=useState(()=>goal.period==="custom"?goal:{...goal,end_date:goalDates(goal.period,goal.start_date).end}),[busy,setBusy]=useState(false);
 function changePeriod(period:Goal["period"]){const dates=goalDates(period);setForm({...form,period,...(period==="custom"?{}:{start_date:dates.start,end_date:dates.end})})}
 async function save(e:FormEvent){e.preventDefault();if(!form.title.trim()||form.end_date<form.start_date)return;setBusy(true);try{await data.update("goals",goal.id,{title:form.title.trim(),description:form.description,period:form.period,start_date:form.start_date,end_date:form.end_date,status:form.status,achieved_at:form.status==="achieved"?(form.achieved_at??new Date().toISOString()):null});onClose()}catch(e){data.setError(e instanceof Error?e.message:"Could not save goal")}finally{setBusy(false)}}
 return <Modal title="Edit goal" onClose={onClose}><form className="dialog-form" onSubmit={save}><label>Title<input autoFocus required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Goal["status"]})}><option value="active">Active</option><option value="achieved">Achieved</option><option value="archived">Archived</option></select></label><label>Time horizon<select value={form.period} onChange={e=>changePeriod(e.target.value as Goal["period"])}><option value="week">By the end of this week</option><option value="month">By the end of this month</option><option value="three_months">Within 3 months</option><option value="six_months">Within 6 months</option><option value="year">Within 1 year</option><option value="custom">Custom dates</option></select></label><div className="form-grid goal-dates"><label>Starts<input type="date" value={form.start_date} disabled={form.period!=="custom"} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label>Target date<input type="date" min={form.start_date} value={form.end_date} disabled={form.period!=="custom"} onChange={e=>setForm({...form,end_date:e.target.value})}/></label></div><GoalWork goal={goal} data={data}/><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={busy||!form.title.trim()||form.end_date<form.start_date}>{busy?"Saving…":"Save goal"}</button></div></form></Modal>
}
function SearchView({data,onTask}:{data:ReturnType<typeof usePlanar>;onTask:(t:Task)=>void}){const[q,setQ]=useState(""),[board,setBoard]=useState(""),[status,setStatus]=useState(""),visibleBoards=data.boards.filter(b=>!b.trashed_at),found=data.tasks.filter(t=>!t.trashed_at&&visibleBoards.some(b=>b.id===t.board_id)&&(!q||t.title.toLowerCase().includes(q.toLowerCase()))&&(!board||t.board_id===board)&&(!status||t.status===status));return <div className="page narrow"><PageHead eyebrow="Across your workspace" title="Search tasks"/><div className="filters"><label><Search/><input autoFocus placeholder="Search titles…" value={q} onChange={e=>setQ(e.target.value)}/></label><select value={board} onChange={e=>setBoard(e.target.value)}><option value="">All boards</option>{visibleBoards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="todo">Todo</option><option value="in_progress">In progress</option><option value="done">Done</option></select></div><p className="muted">{found.length} results</p>{found.map(t=><TaskRow key={t.id} task={t} onClick={()=>onTask(t)}/>)}</div>}
function LifecycleView({data}:{data:ReturnType<typeof usePlanar>}){const archived=data.boards.filter(b=>b.archived_at&&!b.trashed_at),trashedTasks=data.tasks.filter(t=>t.trashed_at),trashedBoards=data.boards.filter(b=>b.trashed_at);return <div className="page"><PageHead eyebrow="Nothing disappears silently" title="Archive & Trash"/><div className="dashboard-grid"><section className="card"><h2>Archived boards</h2>{archived.map(b=><div className="lifecycle-row" key={b.id}><span>{b.name}</span><button onClick={()=>void data.update("boards",b.id,{archived_at:null})}>Restore</button></div>)}{!archived.length&&<p className="muted">No archived boards.</p>}</section><section className="card"><h2>Trashed tasks</h2>{trashedTasks.map(t=><div className="lifecycle-row" key={t.id}><span>{t.title}</span><button onClick={()=>void data.update("tasks",t.id,{trashed_at:null})}>Restore</button></div>)}{!trashedTasks.length&&<p className="muted">Trash is empty.</p>}</section><section className="card"><h2>Trashed boards</h2>{trashedBoards.map(b=><div className="lifecycle-row" key={b.id}><span>{b.name}</span><button onClick={()=>void data.update("boards",b.id,{trashed_at:null})}>Restore</button></div>)}</section></div></div>}

function CreateDialog({kind,board,data,onClose}:{kind:"board"|"folder"|"goal"|"epic";board?:Board;data:ReturnType<typeof usePlanar>;onClose:()=>void}){
 const initial=goalDates("week"),[name,setName]=useState(""),[folder,setFolder]=useState(""),[description,setDescription]=useState(""),[period,setPeriod]=useState<Goal["period"]>("week"),[start,setStart]=useState(initial.start),[end,setEnd]=useState(initial.end);
 function changePeriod(next:Goal["period"]){setPeriod(next);if(next!=="custom"){const dates=goalDates(next);setStart(dates.start);setEnd(dates.end)}}
 async function submit(e:FormEvent){e.preventDefault();if(!name.trim())return;try{if(kind==="folder")await data.insert("folders",{name:name.trim(),position:data.folders.length});if(kind==="board")await data.insert("boards",{name:name.trim(),folder_id:folder||null,position:data.boards.length});if(kind==="epic"&&board)await data.insert("epics",{title:name.trim(),board_id:board.id,position:data.epics.filter(x=>x.board_id===board.id).length});if(kind==="goal")await data.insert("goals",{title:name.trim(),description,period,start_date:start,end_date:end});onClose()}catch(e){data.setError(e instanceof Error?e.message:"Could not create")}}
 return <Modal title={"New "+kind} onClose={onClose}><form className="dialog-form" onSubmit={submit}><label>{kind==="epic"||kind==="goal"?"Title":"Name"}<input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></label>{kind==="board"&&<label>Folder<select value={folder} onChange={e=>setFolder(e.target.value)}><option value="">Unfiled</option>{data.folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}{kind==="goal"&&<><label>Description<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Time horizon<select value={period} onChange={e=>changePeriod(e.target.value as Goal["period"])}><option value="week">By the end of this week</option><option value="month">By the end of this month</option><option value="three_months">Within 3 months</option><option value="six_months">Within 6 months</option><option value="year">Within 1 year</option><option value="custom">Custom dates</option></select></label><div className="form-grid goal-dates"><label>Starts<input type="date" value={start} disabled={period!=="custom"} onChange={e=>setStart(e.target.value)}/></label><label>Target date<input type="date" min={start} value={end} disabled={period!=="custom"} onChange={e=>setEnd(e.target.value)}/></label></div></>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button">Create</button></div></form></Modal>
}

function goalDates(period:Goal["period"],start=localDate()){
 const now=new Date(start+"T12:00:00Z"),endDate=new Date(now);
 if(period==="week")endDate.setUTCDate(now.getUTCDate()+6-(now.getUTCDay()+6)%7);
 else if(period==="month")endDate.setUTCMonth(now.getUTCMonth()+1,0);
 else if(period!=="custom"){
  const months=period==="three_months"?3:period==="six_months"?6:12,day=now.getUTCDate();
  endDate.setUTCDate(1);endDate.setUTCMonth(now.getUTCMonth()+months);
  const lastDay=new Date(Date.UTC(endDate.getUTCFullYear(),endDate.getUTCMonth()+1,0)).getUTCDate();
  endDate.setUTCDate(Math.min(day,lastDay));
 }
 return{start,end:endDate.toISOString().slice(0,10)};
}
