"use client";
import{FormEvent,useEffect,useState}from"react";
import{Archive,ArrowDown,ArrowUp,CalendarDays,Check,ChevronRight,Circle,FolderPlus,Goal as GoalIcon,Home,Menu,Moon,PanelLeftClose,Plus,Search,Sun,Target,Trash2,WifiOff,X}from"lucide-react";
import{usePlanar}from"@/lib/use-planar";
import{localDate,prettyDate,weekStart}from"@/lib/dates";
import type{Activity,Board,Goal,Plan,Task}from"@/lib/types";
import{Empty,Modal,Stat}from"./ui";

type View={kind:"dashboard"|"plan"|"goals"|"search"|"trash"|"board";id?:string;offset?:0|1};
export function PlanarApp({userId,email}:{userId:string;email:string}){
 const data=usePlanar(userId),[view,setView]=useState<View>({kind:"dashboard"}),[mobile,setMobile]=useState(false),[capture,setCapture]=useState(""),[captureBoard,setCaptureBoard]=useState(""),[selected,setSelected]=useState<Task|null>(null),[dialog,setDialog]=useState<"board"|"folder"|"goal"|"epic"|null>(null),[toast,setToast]=useState(""),[online,setOnline]=useState(true);
 const activeBoards=data.boards.filter(b=>!b.archived_at&&!b.trashed_at),board=view.kind==="board"?data.boards.find(b=>b.id===view.id):undefined;
 useEffect(()=>{if(!captureBoard&&activeBoards[0])setCaptureBoard(activeBoards[0].id)},[activeBoards,captureBoard]);
 useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();addEventListener("online",sync);addEventListener("offline",sync);return()=>{removeEventListener("online",sync);removeEventListener("offline",sync)}},[]);
 useEffect(()=>{let day=localDate();const check=()=>{const next=localDate();if(next!==day){day=next;void data.load()}};addEventListener("focus",check);const timer=setInterval(check,60_000);return()=>{removeEventListener("focus",check);clearInterval(timer)}},[]);
 function notify(message:string){setToast(message);setTimeout(()=>setToast(""),2500)}
 async function act(fn:()=>Promise<unknown>,message?:string){try{await fn();if(message)notify(message)}catch(e){data.setError(e instanceof Error?e.message:"Something went wrong")}}
 async function quickAdd(e:FormEvent){e.preventDefault();if(!capture.trim()||!captureBoard)return;const title=capture.trim();setCapture("");await act(()=>data.insert("tasks",{title,board_id:captureBoard,position:data.tasks.filter(t=>t.board_id===captureBoard).length}),"Task added")}
 const nav=(v:View)=>{setView(v);setMobile(false)};
 return <div className="app-shell">
  <aside className={mobile?"sidebar open":"sidebar"}>
   <div className="brand"><div className="brand-mark small">P</div><strong>Planar</strong><button className="mobile-only icon-button" onClick={()=>setMobile(false)}><PanelLeftClose/></button></div>
   <nav aria-label="Main navigation"><Nav active={view.kind==="dashboard"} icon={<Home/>} label="Dashboard" onClick={()=>nav({kind:"dashboard"})}/><Nav active={view.kind==="plan"&&view.offset===0} icon={<Target/>} label="Today" onClick={()=>nav({kind:"plan",offset:0})}/><Nav active={view.kind==="plan"&&view.offset===1} icon={<CalendarDays/>} label="Plan tomorrow" onClick={()=>nav({kind:"plan",offset:1})}/><Nav active={view.kind==="goals"} icon={<GoalIcon/>} label="Goals" onClick={()=>nav({kind:"goals"})}/><Nav active={view.kind==="search"} icon={<Search/>} label="Search" onClick={()=>nav({kind:"search"})}/></nav>
   <div className="side-heading"><span>Boards</span><button onClick={()=>setDialog("folder")} aria-label="New folder"><FolderPlus/></button><button onClick={()=>setDialog("board")} aria-label="New board"><Plus/></button></div>
   <div className="board-tree">{data.folders.map(f=><section key={f.id}><p className="folder-name">{f.name}<button aria-label={"Delete "+f.name} onClick={()=>act(()=>data.remove("folders",f.id),"Folder removed; boards moved to Unfiled")}><X/></button></p>{activeBoards.filter(b=>b.folder_id===f.id).map(b=><BoardLink key={b.id} board={b} active={view.id===b.id} onClick={()=>nav({kind:"board",id:b.id})}/>)}</section>)}<section><p className="folder-name">Unfiled</p>{activeBoards.filter(b=>!b.folder_id).map(b=><BoardLink key={b.id} board={b} active={view.id===b.id} onClick={()=>nav({kind:"board",id:b.id})}/>)}</section></div>
   <div className="sidebar-bottom"><Nav active={view.kind==="trash"} icon={<Trash2/>} label="Archive & Trash" onClick={()=>nav({kind:"trash"})}/><div className="account"><span>{email.slice(0,1).toUpperCase()}</span><div><strong>{email.split("@")[0]}</strong><small>Private workspace</small></div><form action="/api/auth/signout" method="post"><button>Sign out</button></form></div></div>
  </aside>
  <main className="workspace">
   <header className="topbar"><button className="mobile-only icon-button" onClick={()=>setMobile(true)}><Menu/></button><form className="quick-capture" onSubmit={quickAdd}><Plus/><input aria-label="Quick capture task" placeholder="Add a task…" value={capture} onChange={e=>setCapture(e.target.value)}/><select aria-label="Destination board" value={captureBoard} onChange={e=>setCaptureBoard(e.target.value)}>{activeBoards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button disabled={!online||!capture.trim()}>Add</button></form><ThemeButton/></header>
   {!online&&<div className="offline"><WifiOff/> You’re offline. Your input stays here, but changes cannot save until you reconnect.</div>}
   {data.error&&<div className="error-banner" role="alert"><span>{data.error}</span><button onClick={()=>data.setError("")}>Dismiss</button></div>}
   {data.loading?<div className="loading">Gathering your plan…</div>:<>{view.kind==="dashboard"&&<Dashboard {...data} onNavigate={nav} onTask={setSelected}/>} {view.kind==="plan"&&<PlanView offset={view.offset??0} data={data} onTask={setSelected}/>} {view.kind==="board"&&board&&<BoardView board={board} data={data} onTask={setSelected} onEpic={()=>setDialog("epic")} onNavigate={nav}/>} {view.kind==="goals"&&<GoalsView data={data} onNew={()=>setDialog("goal")}/>} {view.kind==="search"&&<SearchView data={data} onTask={setSelected}/>} {view.kind==="trash"&&<LifecycleView data={data}/>}</>}
  </main>
  {selected&&<TaskDetail task={data.tasks.find(t=>t.id===selected.id)??selected} data={data} onClose={()=>setSelected(null)}/>}
  {dialog&&<CreateDialog kind={dialog} board={board} data={data} onClose={()=>setDialog(null)}/>}
  {toast&&<div className="toast"><Check/>{toast}</div>}
 </div>
}
function Nav({active,icon,label,onClick}:{active:boolean;icon:React.ReactNode;label:string;onClick:()=>void}){return <button className={active?"nav-item active":"nav-item"} onClick={onClick}>{icon}<span>{label}</span></button>}
function BoardLink({board,active,onClick}:{board:Board;active:boolean;onClick:()=>void}){return <button className={active?"board-link active":"board-link"} onClick={onClick}><span className="board-dot"/>{board.name}<ChevronRight/></button>}
function ThemeButton(){const[theme,setTheme]=useState("system");useEffect(()=>setTheme(localStorage.getItem("planar-theme")||"system"),[]);function cycle(){const next=theme==="system"?"light":theme==="light"?"dark":"system";setTheme(next);localStorage.setItem("planar-theme",next);document.documentElement.dataset.theme=next}return <button className="icon-button" onClick={cycle} aria-label={"Theme: "+theme}>{theme==="light"?<Sun/>:theme==="dark"?<Moon/>:<span className="system-icon">◐</span>}</button>}
function PageHead({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}){return <div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</div>}
function TaskRow({task,onClick,compact=false}:{task:Task;onClick:()=>void;compact?:boolean}){return <button className={"task-row "+(task.status==="done"?"done ":"")+(compact?"compact":"")} onClick={onClick}><span className="check">{task.status==="done"?<Check/>:<Circle/>}</span><span className="task-main"><strong>{task.title}</strong><small>{[task.priority!=="normal"&&task.priority,task.complexity,task.due_date&&"Due "+task.due_date].filter(Boolean).join(" · ")}</small></span><ChevronRight/></button>}
function Dashboard({tasks,goals,plans,activity,onNavigate,onTask}:{tasks:Task[];goals:Goal[];plans:Plan[];activity:Activity[];onNavigate:(v:View)=>void;onTask:(t:Task)=>void}){
 const today=localDate(),plan=plans.find(p=>p.plan_date===today),items=(plan?.daily_plan_items??[]).map(i=>tasks.find(t=>t.id===i.task_id)).filter(Boolean)as Task[],remaining=items.filter(t=>t.status!=="done"),activeGoals=goals.filter(g=>g.status==="active"&&g.start_date<=today&&g.end_date>=today),completedWeek=activity.filter(a=>a.event==="completed"&&a.occurred_at.slice(0,10)>=weekStart()).length;
 return <div className="page"><PageHead eyebrow={prettyDate(today)} title={plan?.focus||"What matters today?"} action={<button className="button secondary" onClick={()=>onNavigate({kind:"plan",offset:1})}>Plan tomorrow <ChevronRight/></button>}/><div className="stats-grid"><Stat label="Today's plan" value={items.filter(t=>t.status==="done").length+"/"+items.length} detail="tasks complete"/><Stat label="This week" value={completedWeek} detail="completion events"/><Stat label="Active goals" value={activeGoals.length} detail="in this period"/><Stat label="Blocked" value="—" detail="review task links"/></div><div className="dashboard-grid"><section className="card primary-card"><p className="eyebrow">Start here</p>{remaining[0]?<><h2>{remaining[0].title}</h2><p>{remaining[0].notes||"Your first unfinished task for today."}</p><button className="button" onClick={()=>onTask(remaining[0])}>Open task</button></>:<Empty icon={<Check/>} title="The path is clear">Add something to Today or enjoy the breathing room.</Empty>}</section><section className="card"><div className="section-head"><h2>Today</h2><button onClick={()=>onNavigate({kind:"plan",offset:0})}>View plan</button></div>{items.slice(0,5).map(t=><TaskRow key={t.id} task={t} onClick={()=>onTask(t)}/>)}{!items.length&&<p className="muted">Nothing planned yet.</p>}</section><section className="card"><div className="section-head"><h2>Current goals</h2><button onClick={()=>onNavigate({kind:"goals"})}>All goals</button></div>{activeGoals.slice(0,4).map(g=><div className="goal-row" key={g.id}><Target/><div><strong>{g.title}</strong><small>Through {g.end_date}</small></div></div>)}{!activeGoals.length&&<p className="muted">No active goals for today.</p>}</section></div></div>
}
function PlanView({offset,data,onTask}:{offset:0|1;data:ReturnType<typeof usePlanar>;onTask:(t:Task)=>void}){
 const date=localDate(offset),existing=data.plans.find(p=>p.plan_date===date),[focus,setFocus]=useState(existing?.focus??""),[ids,setIds]=useState<string[]>(existing?.daily_plan_items.flatMap(i=>i.task_id?[i.task_id]:[])??[]),[saving,setSaving]=useState(false),[picker,setPicker]=useState(false);
 useEffect(()=>{setFocus(existing?.focus??"");setIds(existing?.daily_plan_items.flatMap(i=>i.task_id?[i.task_id]:[])??[])},[existing?.id,existing?.version,date]);
 const items=ids.map(id=>data.tasks.find(t=>t.id===id)).filter(Boolean)as Task[];
 async function save(nextIds=ids,nextFocus=focus){setSaving(true);try{await data.savePlan(date,nextFocus,nextIds,existing?.version)}catch(e){data.setError(e instanceof Error?e.message:"Plan could not save")}finally{setSaving(false)}}
 function move(i:number,d:number){const next=[...ids],[x]=next.splice(i,1);next.splice(i+d,0,x);setIds(next);void save(next)}
 return <div className="page narrow"><PageHead eyebrow={offset?"Tomorrow":prettyDate(date)} title={offset?"Plan tomorrow":"Today"} action={<span className="save-state">{saving?"Saving…":"Saved"}</span>}/>{offset===1&&<CarryForward data={data} ids={ids} add={id=>{const next=[...ids,id];setIds(next);void save(next)}}/>}<label className="focus-field"><Target/><span>Daily focus<input placeholder="One intention for the day…" value={focus} onChange={e=>setFocus(e.target.value)} onBlur={()=>void save(ids,focus)}/></span></label><div className="section-head"><h2>{offset?"Tomorrow’s order":"Your checklist"}</h2><button className="button secondary" onClick={()=>setPicker(true)}><Plus/>Choose tasks</button></div><div className="plan-list">{items.map((t,i)=><div className="plan-item" key={t.id}><TaskRow task={t} onClick={()=>onTask(t)}/><div className="reorder"><button disabled={i===0} onClick={()=>move(i,-1)} aria-label={"Move "+t.title+" up"}><ArrowUp/></button><button disabled={i===items.length-1} onClick={()=>move(i,1)} aria-label={"Move "+t.title+" down"}><ArrowDown/></button><button onClick={()=>{const next=ids.filter(id=>id!==t.id);setIds(next);void save(next)}} aria-label={"Remove "+t.title}><X/></button></div></div>)}</div>{!items.length&&<Empty icon={<CalendarDays/>} title="An open day">Choose tasks from any board. Nothing carries forward unless you decide it should.</Empty>}{picker&&<TaskPicker tasks={data.tasks.filter(t=>!t.trashed_at&&!t.archived_at)} boards={data.boards} selected={ids} onToggle={id=>{const next=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];setIds(next);void save(next)}} onClose={()=>setPicker(false)}/>}</div>
}
function CarryForward({data,ids,add}:{data:ReturnType<typeof usePlanar>;ids:string[];add:(id:string)=>void}){const today=data.plans.find(p=>p.plan_date===localDate()),left=(today?.daily_plan_items??[]).map(i=>data.tasks.find(t=>t.id===i.task_id)).filter((t):t is Task=>!!t&&t.status!=="done"&&!ids.includes(t.id));if(!left.length)return null;return <div className="carry"><div><strong>Review today’s unfinished work</strong><p>Nothing moves automatically.</p></div>{left.map(t=><button key={t.id} onClick={()=>add(t.id)}><Plus/>{t.title}</button>)}</div>}
function TaskPicker({tasks,boards,selected,onToggle,onClose}:{tasks:Task[];boards:Board[];selected:string[];onToggle:(id:string)=>void;onClose:()=>void}){const[q,setQ]=useState("");return <Modal title="Choose tasks" onClose={onClose}><input className="wide-input" autoFocus placeholder="Find a task…" value={q} onChange={e=>setQ(e.target.value)}/><div className="picker-list">{tasks.filter(t=>t.title.toLowerCase().includes(q.toLowerCase())).map(t=><label key={t.id}><input type="checkbox" checked={selected.includes(t.id)} onChange={()=>onToggle(t.id)}/><span><strong>{t.title}</strong><small>{boards.find(b=>b.id===t.board_id)?.name}</small></span></label>)}</div></Modal>}

function BoardView({board,data,onTask,onEpic,onNavigate}:{board:Board;data:ReturnType<typeof usePlanar>;onTask:(t:Task)=>void;onEpic:()=>void;onNavigate:(v:View)=>void}){
 const[title,setTitle]=useState(""),[view,setListView]=useState<"list"|"kanban">("list"),tasks=data.tasks.filter(t=>t.board_id===board.id&&!t.trashed_at&&!t.archived_at),epics=data.epics.filter(e=>e.board_id===board.id&&!e.trashed_at&&!e.archived_at);
 async function add(e:FormEvent){e.preventDefault();if(!title.trim())return;const value=title.trim();setTitle("");try{await data.insert("tasks",{title:value,board_id:board.id,position:tasks.length})}catch(e){data.setError(e instanceof Error?e.message:"Task could not be added")}}
 async function archive(){const planned=data.plans.some(p=>p.plan_date>=localDate()&&p.daily_plan_items.some(i=>tasks.some(t=>t.id===i.task_id&&t.status!=="done")));if(planned&&!confirm("This board has unfinished work in current or future plans. Archive it while preserving those plan entries?"))return;await data.update("boards",board.id,{archived_at:new Date().toISOString()});onNavigate({kind:"dashboard"})}
 return <div className="page"><PageHead eyebrow={data.folders.find(f=>f.id===board.folder_id)?.name||"Unfiled board"} title={board.name} action={<div className="actions"><button className="icon-button" onClick={()=>setListView(view==="list"?"kanban":"list")} aria-label="Switch view">{view==="list"?<LayoutColumns/>:<LayoutRows/>}</button><button className="button secondary" onClick={onEpic}><Plus/>New epic</button><button className="icon-button" onClick={()=>void archive()} aria-label="Archive board"><Archive/></button></div>}/>
 <form className="board-capture" onSubmit={add}><Plus/><input placeholder={"Add a task to "+board.name} value={title} onChange={e=>setTitle(e.target.value)}/><button className="button">Add task</button></form>
 {view==="list"?<div className="group-list"><TaskGroup title="Standalone" tasks={tasks.filter(t=>!t.epic_id&&!t.parent_id)} onTask={onTask}/>{epics.map(e=><TaskGroup key={e.id} title={e.title} subtitle={tasks.filter(t=>t.epic_id===e.id&&t.status==="done").length+"/"+tasks.filter(t=>t.epic_id===e.id).length+" complete"} tasks={tasks.filter(t=>t.epic_id===e.id&&!t.parent_id)} onTask={onTask}/>)}</div>:<div className="kanban">{(["todo","in_progress","done"]as const).map(s=><section key={s}><h3>{s==="in_progress"?"In progress":s[0].toUpperCase()+s.slice(1)}</h3>{tasks.filter(t=>t.status===s&&!t.parent_id).map(t=><TaskRow key={t.id} task={t} compact onClick={()=>onTask(t)}/>)}</section>)}</div>}
 {!tasks.length&&<Empty icon={<Circle/>} title="A fresh board">Capture a task with only a title. Add structure when it earns its place.</Empty>}</div>
}
function LayoutColumns(){return <span aria-hidden>▦</span>}function LayoutRows(){return <span aria-hidden>☷</span>}
function TaskGroup({title,subtitle,tasks,onTask}:{title:string;subtitle?:string;tasks:Task[];onTask:(t:Task)=>void}){return <section className="task-group"><div className="section-head"><h2>{title}</h2>{subtitle&&<small>{subtitle}</small>}</div>{tasks.map(t=><TaskRow key={t.id} task={t} onClick={()=>onTask(t)}/>)}{!tasks.length&&<p className="muted">No tasks in this group.</p>}</section>}

function TaskDetail({task,data,onClose}:{task:Task;data:ReturnType<typeof usePlanar>;onClose:()=>void}){
 const[form,setForm]=useState(task),[sub,setSub]=useState(""),[link,setLink]=useState(""),[busy,setBusy]=useState(false),children=data.tasks.filter(t=>t.parent_id===task.id&&!t.trashed_at),other=data.tasks.filter(t=>t.id!==task.id&&!t.parent_id&&!t.trashed_at);
 async function save(){setBusy(true);try{await data.update("tasks",task.id,{title:form.title,notes:form.notes,acceptance_criteria:form.acceptance_criteria,status:form.status,complexity:form.complexity||null,priority:form.priority,due_date:form.due_date||null,board_id:form.board_id,epic_id:form.epic_id||null});onClose()}catch(e){data.setError(e instanceof Error?e.message:"Could not save")}finally{setBusy(false)}}
 async function status(){if(task.status!=="done"&&children.some(t=>t.status!=="done")&&!confirm("Some subtasks are unfinished. Complete the parent without completing them?"))return;const next=task.status==="done"?"todo":"done";await data.update("tasks",task.id,{status:next});setForm({...form,status:next})}
 async function addSub(e:FormEvent){e.preventDefault();if(!sub.trim())return;await data.insert("tasks",{title:sub.trim(),board_id:task.board_id,epic_id:task.epic_id,parent_id:task.id,position:children.length});setSub("")}
 async function addLink(){if(!link)return;try{await data.insert("task_relationships",{source_task_id:task.id,target_task_id:link,kind:"blocked_by"});setLink("")}catch(e){data.setError(e instanceof Error?e.message:"Could not add dependency")}}
 return <Modal title="Task details" onClose={onClose}><div className="task-detail"><button className={task.status==="done"?"complete-toggle done":"complete-toggle"} onClick={()=>void status()}>{task.status==="done"?<Check/>:<Circle/>}{task.status==="done"?"Completed":"Mark complete"}</button><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-grid"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Task["status"]})}><option value="todo">Todo</option><option value="in_progress">In progress</option><option value="done">Done</option></select></label><label>Board<select value={form.board_id} onChange={e=>setForm({...form,board_id:e.target.value,epic_id:null})}>{data.boards.filter(b=>!b.trashed_at).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Epic<select value={form.epic_id??""} onChange={e=>setForm({...form,epic_id:e.target.value||null})}><option value="">Standalone</option>{data.epics.filter(ep=>ep.board_id===form.board_id&&!ep.trashed_at).map(ep=><option key={ep.id} value={ep.id}>{ep.title}</option>)}</select></label><label>Complexity<select value={form.complexity??""} onChange={e=>setForm({...form,complexity:(e.target.value||null)as Task["complexity"]})}><option value="">Not set</option><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Task["priority"]})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label><label>Due date<input type="date" value={form.due_date??""} onChange={e=>setForm({...form,due_date:e.target.value||null})}/></label></div><label>Notes<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label>Acceptance criteria<textarea rows={3} value={form.acceptance_criteria} onChange={e=>setForm({...form,acceptance_criteria:e.target.value})}/></label>
 <section><h3>Subtasks</h3>{children.map(t=><TaskRow key={t.id} task={t} compact onClick={()=>{}}/>)}{!task.parent_id&&<form className="inline-form" onSubmit={addSub}><input placeholder="Add a subtask…" value={sub} onChange={e=>setSub(e.target.value)}/><button><Plus/></button></form>}</section>
 <section><h3>Blocked by</h3><div className="inline-form"><select value={link} onChange={e=>setLink(e.target.value)}><option value="">Choose task…</option>{other.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button type="button" onClick={()=>void addLink()}><Plus/></button></div><small>Dependencies warn; they do not prevent progress.</small></section>
 <div className="modal-actions"><button className="danger-link" onClick={()=>{if(confirm("Move this task to Trash?"))void data.update("tasks",task.id,{trashed_at:new Date().toISOString()}).then(onClose)}}><Trash2/>Move to Trash</button><button className="button" disabled={busy||!form.title.trim()} onClick={()=>void save()}>{busy?"Saving…":"Save changes"}</button></div></div></Modal>
}

function GoalsView({data,onNew}:{data:ReturnType<typeof usePlanar>;onNew:()=>void}){return <div className="page"><PageHead eyebrow="Outcomes, not scores" title="Goals" action={<button className="button" onClick={onNew}><Plus/>New goal</button>}/><div className="goal-grid">{data.goals.map(g=><article className={"goal-card "+g.status} key={g.id}><div><span className="pill">{g.period}</span><span className="goal-status">{g.status}</span></div><h2>{g.title}</h2><p>{g.description||"No description"}</p><small>{g.start_date} → {g.end_date}</small>{g.status==="active"&&<button onClick={()=>void data.update("goals",g.id,{status:"achieved",achieved_at:new Date().toISOString()})}><Check/>Mark achieved</button>}</article>)}</div>{!data.goals.length&&<Empty icon={<Target/>} title="Name the outcome">Goals stay active until you explicitly mark them achieved.</Empty>}</div>}
function SearchView({data,onTask}:{data:ReturnType<typeof usePlanar>;onTask:(t:Task)=>void}){const[q,setQ]=useState(""),[board,setBoard]=useState(""),[status,setStatus]=useState("");const found=data.tasks.filter(t=>!t.trashed_at&&(!q||t.title.toLowerCase().includes(q.toLowerCase()))&&(!board||t.board_id===board)&&(!status||t.status===status));return <div className="page narrow"><PageHead eyebrow="Across your workspace" title="Search tasks"/><div className="filters"><label><Search/><input autoFocus placeholder="Search titles…" value={q} onChange={e=>setQ(e.target.value)}/></label><select value={board} onChange={e=>setBoard(e.target.value)}><option value="">All boards</option>{data.boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="todo">Todo</option><option value="in_progress">In progress</option><option value="done">Done</option></select></div><p className="muted">{found.length} results</p>{found.map(t=><TaskRow key={t.id} task={t} onClick={()=>onTask(t)}/>)}</div>}
function LifecycleView({data}:{data:ReturnType<typeof usePlanar>}){const archived=data.boards.filter(b=>b.archived_at&&!b.trashed_at),trashedTasks=data.tasks.filter(t=>t.trashed_at),trashedBoards=data.boards.filter(b=>b.trashed_at);return <div className="page"><PageHead eyebrow="Nothing disappears silently" title="Archive & Trash"/><div className="dashboard-grid"><section className="card"><h2>Archived boards</h2>{archived.map(b=><div className="lifecycle-row" key={b.id}><span>{b.name}</span><button onClick={()=>void data.update("boards",b.id,{archived_at:null})}>Restore</button></div>)}{!archived.length&&<p className="muted">No archived boards.</p>}</section><section className="card"><h2>Trashed tasks</h2>{trashedTasks.map(t=><div className="lifecycle-row" key={t.id}><span>{t.title}</span><button onClick={()=>void data.update("tasks",t.id,{trashed_at:null})}>Restore</button></div>)}{!trashedTasks.length&&<p className="muted">Trash is empty.</p>}</section><section className="card"><h2>Trashed boards</h2>{trashedBoards.map(b=><div className="lifecycle-row" key={b.id}><span>{b.name}</span><button onClick={()=>void data.update("boards",b.id,{trashed_at:null})}>Restore</button></div>)}</section></div></div>}

function CreateDialog({kind,board,data,onClose}:{kind:"board"|"folder"|"goal"|"epic";board?:Board;data:ReturnType<typeof usePlanar>;onClose:()=>void}){
 const[name,setName]=useState(""),[folder,setFolder]=useState(""),[description,setDescription]=useState(""),[period,setPeriod]=useState<"week"|"month"|"custom">("week"),[start,setStart]=useState(localDate()),[end,setEnd]=useState(localDate(7));
 async function submit(e:FormEvent){e.preventDefault();if(!name.trim())return;try{if(kind==="folder")await data.insert("folders",{name:name.trim(),position:data.folders.length});if(kind==="board")await data.insert("boards",{name:name.trim(),folder_id:folder||null,position:data.boards.length});if(kind==="epic"&&board)await data.insert("epics",{title:name.trim(),board_id:board.id,position:data.epics.filter(x=>x.board_id===board.id).length});if(kind==="goal")await data.insert("goals",{title:name.trim(),description,period,start_date:start,end_date:end});onClose()}catch(e){data.setError(e instanceof Error?e.message:"Could not create")}}
 return <Modal title={"New "+kind} onClose={onClose}><form className="dialog-form" onSubmit={submit}><label>{kind==="epic"||kind==="goal"?"Title":"Name"}<input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></label>{kind==="board"&&<label>Folder<select value={folder} onChange={e=>setFolder(e.target.value)}><option value="">Unfiled</option>{data.folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}{kind==="goal"&&<><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="form-grid"><label>Period<select value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="week">Week</option><option value="month">Month</option><option value="custom">Custom</option></select></label><label>Starts<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Ends<input type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label></div></>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button">Create</button></div></form></Modal>
}
